# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your API keys

[openai]
api_key = " your api key"

[gemini]
api_key = " your api key"

[anthropic]
api_key = " your api key"

# Optional: Add other configuration
[app]
title = "AI Code Reviewer"
description = "Professional code review powered by AI"